FROM python:3.9
COPY requirements.txt /requirements.txt
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /requirements.txt

ENV PYTHONPATH=/

EXPOSE 5001
CMD ["python", "-u", "server.py"]