name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: micalabs/mica
      TAG: latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run build_docker.sh script
        run: |
          chmod +x ./build_docker.sh
          ./build_docker.sh "${{ env.REPO_NAME }}:${{ env.TAG }}"

      - name: Push Docker image to Docker Hub
        run: docker push "${{ env.REPO_NAME }}:${{ env.TAG }}"
